package com.tamkeen.backoffice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserResponseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponseAllPropertiesEquals(UserResponse expected, UserResponse actual) {
        assertUserResponseAutoGeneratedPropertiesEquals(expected, actual);
        assertUserResponseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponseAllUpdatablePropertiesEquals(UserResponse expected, UserResponse actual) {
        assertUserResponseUpdatableFieldsEquals(expected, actual);
        assertUserResponseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponseAutoGeneratedPropertiesEquals(UserResponse expected, UserResponse actual) {
        assertThat(expected)
            .as("Verify UserResponse auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponseUpdatableFieldsEquals(UserResponse expected, UserResponse actual) {
        assertThat(expected)
            .as("Verify UserResponse relevant properties")
            .satisfies(e -> assertThat(e.getResponseDate()).as("check responseDate").isEqualTo(actual.getResponseDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponseUpdatableRelationshipsEquals(UserResponse expected, UserResponse actual) {
        assertThat(expected)
            .as("Verify UserResponse relationships")
            .satisfies(e -> assertThat(e.getAnswer()).as("check answer").isEqualTo(actual.getAnswer()))
            .satisfies(e -> assertThat(e.getQuestion()).as("check question").isEqualTo(actual.getQuestion()));
    }
}
